# Configuração do mkinitcpio para a ISO do Edenland
# Necessário para o correto funcionamento do 'Switch Root'

HOOKS=(base udev memdisk archiso archiso_loop_mnt block filesystems keyboard)

# Compressão recomendada para ISOs
COMPRESSION="xz"
COMPRESSION_OPTIONS=('-9e')
